name: te-orbit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=2.3.5
  - pandas=2.3.3
  - networkx=3.6
  - matplotlib=3.10.7
  - scipy=1.16.3
  - pulp=3.3.0
  - cvxpy=1.7.4
  - osqp=1.0.5
  - scs=3.2.9
  - pip
  - pip:
      - jupyter
      - ipykernel

# NOTE: ORBIT is NOT included here.
# It must be installed manually from the proprietary Quantum Dice distribution.
